set -e
true
/home/gbonilla/anaconda3/bin/python /home/gbonilla/Software/BioTools/SPAdes-3.14.0-Linux/share/spades/spades_pipeline/scripts/preprocess_contigs.py --args_filename /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/split_input/tmp/contigs --dst /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/split_input --threshold_for_breaking_additional_contigs 10
true
true
/home/gbonilla/Software/BioTools/SPAdes-3.14.0-Linux/bin/spades-hammer /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/corrected/configs/config.info
/home/gbonilla/anaconda3/bin/python /home/gbonilla/Software/BioTools/SPAdes-3.14.0-Linux/share/spades/spades_pipeline/scripts/compress_all.py --input_file /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/corrected/corrected.yaml --ext_python_modules_home /home/gbonilla/Software/BioTools/SPAdes-3.14.0-Linux/share/spades --max_threads 35 --output_dir /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/corrected --not_used_yaml_file /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/corrected/dont_correct.yaml --gzip_output
true
true
/home/gbonilla/Software/BioTools/SPAdes-3.14.0-Linux/bin/spades-core /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/K21/configs/config.info /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/K21/configs/careful_mode.info
/home/gbonilla/Software/BioTools/SPAdes-3.14.0-Linux/bin/spades-core /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/K33/configs/config.info /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/K33/configs/careful_mode.info
/home/gbonilla/Software/BioTools/SPAdes-3.14.0-Linux/bin/spades-core /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/K55/configs/config.info /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/K55/configs/careful_mode.info
/home/gbonilla/Software/BioTools/SPAdes-3.14.0-Linux/bin/spades-core /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/K77/configs/config.info /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/K77/configs/careful_mode.info
/home/gbonilla/Software/BioTools/SPAdes-3.14.0-Linux/bin/spades-core /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/K99/configs/config.info /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/K99/configs/careful_mode.info
/home/gbonilla/Software/BioTools/SPAdes-3.14.0-Linux/bin/spades-core /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/K127/configs/config.info /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/K127/configs/careful_mode.info
/home/gbonilla/anaconda3/bin/python /home/gbonilla/Software/BioTools/SPAdes-3.14.0-Linux/share/spades/spades_pipeline/scripts/copy_files.py /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/K127/before_rr.fasta /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/before_rr.fasta /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/K127/final_contigs.fasta /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/contigs.fasta /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/K127/first_pe_contigs.fasta /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/first_pe_contigs.fasta /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/K127/scaffolds.fasta /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/scaffolds.fasta /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/K127/scaffolds.paths /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/scaffolds.paths /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/K127/assembly_graph_with_scaffolds.gfa /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/assembly_graph_with_scaffolds.gfa /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/K127/assembly_graph.fastg /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/assembly_graph.fastg /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/K127/final_contigs.paths /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/contigs.paths
true
true
/home/gbonilla/anaconda3/bin/python /home/gbonilla/Software/BioTools/SPAdes-3.14.0-Linux/share/spades/spades_pipeline/scripts/correction_iteration_script.py --corrected /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/contigs.fasta --assembled /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/misc/assembled_contigs.fasta --assembly_type contigs --output_dir /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined --bin_home /home/gbonilla/Software/BioTools/SPAdes-3.14.0-Linux/bin
/home/gbonilla/anaconda3/bin/python /home/gbonilla/Software/BioTools/SPAdes-3.14.0-Linux/share/spades/spades_pipeline/scripts/correction_iteration_script.py --corrected /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/scaffolds.fasta --assembled /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/misc/assembled_scaffolds.fasta --assembly_type scaffolds --output_dir /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined --bin_home /home/gbonilla/Software/BioTools/SPAdes-3.14.0-Linux/bin
true
/home/gbonilla/anaconda3/bin/python /home/gbonilla/Software/BioTools/SPAdes-3.14.0-Linux/share/spades/spades_pipeline/scripts/breaking_scaffolds_script.py --result_scaffolds_filename /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/scaffolds.fasta --misc_dir /home/gbonilla/Documents/Bifido/genomesDIC19/05_refinedAssembly/T369_3_refined/misc --threshold_for_breaking_scaffolds 3
true
